### PR TITLE
Update googleauth dependency

### PR DESCRIPTION
**Pull request by blowmage**
Allow the dependency to use the 0.7.x releases.

### CODE REVIEW

**Comment by jbolinger** [comment]
@landrito do you know if this version was pinned for any reason?

@blowmage I assume that you've already tested this with the cloud apis?

**Comment by landrito** [comment]
I remember no reason why it was pinned so strictly. Sorry! LGTM assuming some hand tests show nothing breaks.

**Comment by blowmage** [comment]
> @blowmage I assume that you've already tested this with the cloud apis?

Not yet. This PR is part of incorporating some new functionality released in the latest version of googleauth into the cloud gems.

**Comment by jbolinger** [comment]
@blowmage have you been able to test it with this updated auth version?

**Comment by blowmage** [comment]
No, I have not. Isn't making the change and running this repo's existing CI sufficient?

**Comment by jbolinger** [comment]
That's sufficient to merge but I don't think the existing CI runs any real tests so I would like to verify before releasing it. Do you need one soon?

**Comment by blowmage** [comment]
I've tested this against google-cloud-ruby with googleauth 0.7.1 and everything works as expected.

**Comment by blowmage** [comment]
I noticed this PR was out of date. I have updated it to the latest `master`. Can someone take a look?

**Comment by jbolinger** [comment]
Thanks for verifying with google-cloud-ruby @blowmage! I'll merge it now.

**Pull request merged**
