### PR TITLE
Update gapic generated code for longrunning operation

### PR DESCRIPTION
**Pull request by swcloud**

### CODE REVIEW

**Comment by landrito** [comment]
Hmm seems Rubocop is now flagging files that you didn't change. Do you have any idea why?

**Comment by swcloud** [comment]
In your PR https://github.com/googleapis/gax-ruby/pull/47, the check was passing. That's strange.

**Comment by landrito** [comment]
I actually added some code to fix the travis error in #47 since it was so small.

**Comment by swcloud** [comment]
You don't have this offense reported?

`lib/google/gax/api_callable.rb:337:7: C: Block has too many lines. [26/25]
      proc do |request| ...
      ^^^^^^^^^^^^^^^^^`

**Comment by swcloud** [comment]
@landrito PTAL

**Pull request merged**
