### PR TITLE
Return master branch to 1.x development

### PR DESCRIPTION
**Pull request by dazuma**
The 2.0 development has been moved into https://github.com/googleapis/gapic-generator-ruby so we are switching master back to 1.x. I can't rebase master in this repo, so this includes a commit that reverts all the 2.0 development, and then merges in the existing 1.x branch.

Notes:
* I verified via git diff that the contents of this commit are identical to the current state of the 1.x branch.
* I left a branch "2.x-old" to mark the final extent of the 2.0 development in this repo.

### CODE REVIEW

**Comment by dazuma** [comment]
This reverts commits, and merges a bunch of commits that were already CLA-covered.

**Comment by blowmage** [comment]
Did you try renaming master to 2.x and then renaming 1.x to master?

**Comment by dazuma** [comment]
@blowmage Master branch protection won't let me 😞

**Comment by dazuma** [comment]
Obsolete.

**Pull request closed without merging**
