### PR TITLE
Remove params_extractor

### LINKED ISSUE #173: Remove params_extractor
This functionality should be moved out of GAX to the client.

### PR DESCRIPTION
**Pull request by blowmage**
[closes #173]

### CODE REVIEW

**Comment by jbolinger** [comment]
Let's update https://github.com/googleapis/gapic-generator-ruby/issues/104 and/or open a PR in the generator to accompany this one so we can see how the usage of this will look from the client side.

**Comment by blowmage** [comment]
I have updated googleapis/gapic-generator-ruby#94 to be more up to date with the changes made in the GAPIC generator and in Gax. It removes params_extractor from Gax entirely, and demonstrates how the GAPIC generator client can provide that type of functionality.

**Comment by jbolinger** [comment]
@blowmage I did a quick pass on https://github.com/googleapis/gapic-generator-ruby/pull/94, but it looks like this functionality is still a WIP?

**Comment by blowmage** [comment]
googleapis/gapic-generator-ruby#94 is a working branch that demonstrates that features can be moved from Gax to the generator. Much of what that branch is using is available to review in #178. Not all of it, but most of it.

**Comment by blowmage** [comment]
This is satisfied by #178.

**Pull request closed without merging**
